### ISSUE TITLE
Cannot "apply" changes.

### ISSUE THREAD

**Issue by BrianDmyszewicz** [flathub/io.github.realmazharhussain.GdmSettings#1]
The app installs and launches but isn't able to apply changes, it doesn't even ask for the password upon pressing "apply", the application itself works but this flatpak version of it seems to be broken. I tried installing it both system-wide and as --user with no success. This bug occurs on Arch Linux, kernel 5.17.5-arch1-1 and flatpak 1.12.7 but I suppose it also persists on other versions and distributions. I'm guessing it's a permissions/sandboxing issue.

**Comment by realmazharhussain** [comment]
Hi, I'm sorry that it took so long to reply.

Is the flatpak working now?
